# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [6]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [4]:
my_list = [23, 4, 0, 24, 19, 21, 0] 
my_arr = np.array([23, 4, 0, 24, 19, 21, 0] )

2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [5]:
print(my_list * 4)
# Multiplying my_list by 4 will duplicate the items in the list 4 times.
print(my_arr * 4)
# Multiplying my_arr by 4 will multiply each value in the list by 4. 

[23, 4, 0, 24, 19, 21, 0, 23, 4, 0, 24, 19, 21, 0, 23, 4, 0, 24, 19, 21, 0, 23, 4, 0, 24, 19, 21, 0]
[92 16  0 96 76 84  0]


3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [7]:
print(my_list + my_list)
# Adding my_list with my_list will append the list to create a larger list. It is the same as my_list * 2.
print(my_arr + my_arr)
# Adding my_arr with my_arr will add each respective value in the list.

[23, 4, 0, 24, 19, 21, 0, 23, 4, 0, 24, 19, 21, 0]
[46  8  0 48 38 42  0]


4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [8]:
print(my_list - my_list)
# You get an error.
print(my_arr - my_arr)
# Subtracting my_arr with my_arr will subtract each respective value in the list.

TypeError: unsupported operand type(s) for -: 'list' and 'list'

5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [ ]:
print(my_list * my_list)
# You get an error.
print(my_arr * my_arr)
# Multiplying my_arr with my_arr will multiply each respective value in the list.

7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [10]:
print(my_list / my_list)
# You get an error.
print(my_arr / my_arr)
# Diving my_arr with my_arr will divide each respective value in the list.

TypeError: unsupported operand type(s) for /: 'list' and 'list'

8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

In [16]:
# Arrays can be manipulated more than lists, as seen with errors received from list when subtracting, multiplying, and dividing. Wheen using functions that work, it impacts the list as a whole while it impacts each art in an array.

## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [12]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array[2][1]

8

In [13]:
multiDimensionalArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def secondArrayValue(array):
    # Takes given multi-dimensional array and returns an array comprised of every second value. 
    secondArrayValue = []
    for i in range(0, len(array)):
       secondArrayValue = np.append(secondArrayValue, array[i][1])
    return secondArrayValue

secondArrayValue(multiDimensionalArray)

array([2., 5., 8.])

In 2-3 sentences, describe what section of the website helped you write your function. 

In [54]:
# Numpy Array Indexing was the most helpful to me. I knew what I wanted to do but was messing up the syntax and how to properly word things. That section helped me understand how to write parts of the code. 

How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [62]:
array = np.array([[1, 2, 7, 5, 9], [1, 5, 8, 4, 1], [1, 6, 9, 3, 8]])
arrayTwo = np.array([[1, 7, 2], [6, 2, 7], [1, 7, 9]])

def sortMultiDimensionalArrays(array):
    # Takes a multi-dimensional array with equal lengths and sorts the elements in reach part then sorts arrays based on the mean from least to greatest. 
    array = np.sort(array)
    # Sorts each element in numerical order. 
    meanOfArrays = []
    sortedArray = [] 
    for i in range(0, len(array)):
        meanOfArrays = np.append(meanOfArrays, np.mean(array[i]))
    meanOfArrays = np.sort(meanOfArrays)
    # Gets the means of the arrays and sorts them.
    for i in range(0, len(array)):
        for j in range(0, len(array)):
            if np.mean(array[j]) == meanOfArrays[i]:
                sortedArray = np.append(sortedArray, np.array(array[j]))
    # Gets the order of the arrays. 
    return sortedArray.reshape(len(array), len(array[0]))

print(sortMultiDimensionalArrays(array))
print(sortMultiDimensionalArrays(arrayTwo))

[[1. 1. 4. 5. 8.]
 [1. 2. 5. 7. 9.]
 [1. 3. 6. 8. 9.]]
[[1. 2. 7.]
 [2. 6. 7.]
 [1. 7. 9.]]


In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [67]:
# I took inspiration from Numpy Array Sort with examples such as Sorting Arrays, and Sorting a 2-D Array. 

# Sorting Arrays
array = np.array([5, 3, 8, 1, 3])
arrayTwo = np.array([3, 4, 7, 3, 8, 1, 10])

print(np.sort(array))
print(np.sort(arrayTwo))
# Sorts arrays in numerical order.

# Sorting Arrays (String)
array = np.array(['Mecury', 'Venus', 'Mars'])
arrayTwo = np.array(['String', 'Integer', 'Float'])

print(np.sort(array))
print(np.sort(arrayTwo))
# Sorts arrays in alphabetical order.

array = np.array([[3, 2, 4, 4, 3, 8], [0, 1, 2, 8, 2, 1]])
arrayTwo = np.array([[1, 3, 7, 9, 20, 4], [1, 2, 4, 3, 0, 1]])

print(np.sort(array))
print(np.sort(arrayTwo))
# Sorts each array in numerical order. 

[1 3 3 5 8]
[ 1  3  3  4  7  8 10]
['Mars' 'Mecury' 'Venus']
['Float' 'Integer' 'String']
[[2 3 3 4 4 8]
 [0 1 1 2 2 8]]
[[ 1  3  4  7  9 20]
 [ 0  1  1  2  3  4]]


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

In [68]:
# I saw the sort function and wanted to use it and saw how it sorted each indiviudal array in a multidimensional array. I wanted to make it so that each array would be sorted by their mean value, so I used the sort an dmean functions to get it to work.

# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [79]:
from evenSum import sumEvenNumbers as sen

Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [80]:
list = [3, 2, 4, 4, 3, 8, 0, 1, 2, 8, 2, 1]
sen(list)

30

I have provided you a separate module called `example.py`. Import that module here.

In [89]:
import example as ex

With the following variables, use my module to show which of the rocket's escape!

In [86]:
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 10000],  # Rocket 2
    [3000, 3100, 3200, 3300]    # Rocket 3
])

mass_of_planet = 5.972e24 # kilograms
radius_of_planet = 6.371e6 # meters

In [92]:
ex.rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet)

['Rocket left the planet!',
 'Rocket is orbiting around the planet.',
 'Rocket crashes back into the planet!']

In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

In [91]:
# It follows "good coding practices" in that all of the titles make sense with the code, there are detailed comments about each part, and it is readable. Right now, the only bit of room for improvement is the name of the code. "example.py" does not describe what the program does well.  

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

In [8]:
# First, my module determines the distance needed for a bird, travelling a given velocity and at a certain height, to lay droppings on a person. Then it determines if the bird will be able to mak this distance and then travel 100 meters, given they have a break after dropping

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?

In [30]:
# The most challenging part of building this module was making sure that every variable was right. Having variables be different helped in making sense of wht should be what and I should apply this to future coding assignments. 

Once your module is complete, import it here.

In [5]:
import twoDimensionalMotion as dm

Call each of your functions in the cell below. Make sure to show the outputs! 

In [7]:
distanceBirdsCanTravel = np.array([[20, 50], [10, 10], [20, 10], [0, 0]])
dm.birdStatus(10, 0, 20, distanceBirdsCanTravel)

['Bird does not let out droppings.',
 'Bird does not let out droppings.',
 'Bird does not let out droppings.',
 'Bird is asleep.']

# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!